version: '3.8'

services:
  rrr-tracker:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: rrr_robot_container
    network_mode: host
    stdin_open: true
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${HOME}/.Xauthority
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:${HOME}/.Xauthority
