version: '3.8'

services:
  rrr-tracker:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: rrr_robot_container
    volumes:
      - .:/app
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
